on:
  push:
    branches:
      - "main"

name: "Main Branch"

# Secrets:
# * CACHE_VERSION - Set to `date +%s`, set new when the cache should be busted

jobs:
  detectToolVersions:
    name: "Detect Tool Versions"

    uses: jshmrtn/expo/.github/workflows/part_tool_versioning.yml@main

  test:
    name: "Test"

    needs: ['detectToolVersions']

    uses: jshmrtn/expo/.github/workflows/part_test.yml@main
    with:
      elixirVersion: "${{ needs.detectToolVersions.outputs.elixirVersion }}"
      otpVersion: "${{ needs.detectToolVersions.outputs.otpVersion }}"
    secrets:
      CACHE_VERSION: "${{ secrets.CACHE_VERSION }}"

  docs:
    name: "Docs"

    needs: ['detectToolVersions']

    uses: jshmrtn/expo/.github/workflows/part_docs.yml@main
    with:
      elixirVersion: "${{ needs.detectToolVersions.outputs.elixirVersion }}"
      otpVersion: "${{ needs.detectToolVersions.outputs.otpVersion }}"
    secrets:
      CACHE_VERSION: "${{ secrets.CACHE_VERSION }}"
