on:
  push:
    branches:
      - "main"

name: "Main Branch"

# Secrets:
# * CACHE_VERSION - Set to `date +%s`, set new when the cache should be busted

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml
    with:
      elixirVersion: "1.13.4"
      otpVersion: "25.0.2"
    secrets:
      CACHE_VERSION: "${{ secrets.CACHE_VERSION }}"

  docs:
    name: "Docs"

    uses: ./.github/workflows/part_docs.yml
    with:
      elixirVersion: "1.13.4"
      otpVersion: "25.0.2"
    secrets:
      CACHE_VERSION: "${{ secrets.CACHE_VERSION }}"
