on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

name: "Pull Request"

# Secrets:
# * CACHE_VERSION - Set to `date +%s`, set new when the cache should be busted

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml
    with:
      elixirVersion: "1.13.4-otp-25"
      otpVersion: "25.0.2"
    secrets:
      CACHE_VERSION: "${{ secrets.CACHE_VERSION }}"

  docs:
    name: "Docs"

    needs: ["detectToolVersions"]

    uses: ./.github/workflows/part_docs.yml
    with:
      elixirVersion: "1.13.4-otp-25"
      otpVersion: "25.0.2"
    secrets:
      CACHE_VERSION: "${{ secrets.CACHE_VERSION }}"

  dependabot:
    name: "Dependabot"

    needs: ["test", "docs"]

    uses: ./.github/workflows/part_dependabot.yml
