on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

name: "Pull Request"

permissions:
  contents: read

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml
    with:
      elixirVersion: "1.18"
      otpVersion: "27.2"

  docs:
    name: "Docs"

    permissions:
      contents: write

    uses: ./.github/workflows/part_docs.yml
    with:
      elixirVersion: "1.18"
      otpVersion: "27.2"
