on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch: {}

name: "Pull Request"

jobs:
  test:
    name: "Test"

    uses: ./.github/workflows/part_test.yml
    with:
      elixirVersion: "1.17.2"
      otpVersion: "27.0.1"

  docs:
    name: "Docs"

    uses: ./.github/workflows/part_docs.yml
    with:
      elixirVersion: "1.17.2"
      otpVersion: "27.0.1"
