on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

name: "Stable Tag"

jobs:
  release:
    name: Create Release

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release create \
            --repo ${{ github.repository }} \
            --title ${{ github.ref_name }} \
            --notes '' \
            --draft \
            ${{ github.ref_name }}

  docs:
    name: "Docs"

    needs: ["release"]

    uses: ./.github/workflows/part_docs.yml
    with:
      elixirVersion: "1.17.2"
      otpVersion: "27.0.1"
      releaseName: "${{ github.ref_name }}"
